require 'openid/store/filesystem'
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :twitter, '0bSz3URebktk4tC5MInbw', '5NjsAmAFhNlJHjYM6OllhJunEsVYmT1c9KDJzzKW8'
  
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'wf', :domain => 'wf.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'jp', :domain => 'jp.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'bl', :domain => 'bl.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'in', :domain => 'in.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'pfs', :domain => 'pfs.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'bg', :domain => 'bg.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'kn', :domain => 'kn.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'hs', :domain => 'hs.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'si', :domain => 'si.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'fz', :domain => 'fz.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'ko', :domain => 'ko.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'mg', :domain => 'mg.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'sk', :domain => 'sk.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'jn', :domain => 'jn.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'mb', :domain => 'mb.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'nb', :domain => 'nb.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'dc', :domain => 'dc.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'sr', :domain => 'sr.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'md', :domain => 'md.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'pa', :domain => 'pa.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'sjw', :domain => 'sjw.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'sb', :domain => 'sb.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'vbl', :domain => 'vbl.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'wb', :domain => 'wb.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'w1', :domain => 'w1.justbooksclc.com'
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'nwh', :domain => 'nwh.justbooksclc.com'
  
  provider :google_apps, OpenID::Store::Filesystem.new('/tmp'), :name => 'strata', :domain => 'strata.co.in'
  
end